CREATE TABLE ia_utm.bienestar.formulario (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    num_ficha INT NOT NULL,
    
    provincia VARCHAR(100),
    ciudad VARCHAR(100),
    parroquia VARCHAR(100),
    est_si BOOLEAN default false,
    est_no BOOLEAN default false,
    inst_utm BOOLEAN default false,
    inst_otro BOOLEAN default false,
    inst_texto VARCHAR(200),
    facultad VARCHAR(100),
    carrera VARCHAR(100),
    mod_p BOOLEAN default false,
    mod_h BOOLEAN default false,
    mod_l BOOLEAN default false,
    nivel VARCHAR(50),
    
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    cedula VARCHAR(20),
    celular VARCHAR(20),
    correo VARCHAR(150),
    edad INT,
    fecha_nac DATE,
    nacionalidad VARCHAR(100),
    sex_f BOOLEAN default false,
    sex_m BOOLEAN default false,
    sex_otro BOOLEAN default false,
    sex_texto VARCHAR(200),
    identidad_genero VARCHAR(200),
    direccion VARCHAR(200),
    lugar_residencia VARCHAR(200),
    contacto_ref VARCHAR(200),
    
    gine BOOLEAN default false,
   	lc BOOLEAN default false,
   	v BOOLEAN default false,
   	s BOOLEAN default false,
   	hb BOOLEAN default false,
   	hc BOOLEAN default false,
   	pe BOOLEAN default false,
   	aj BOOLEAN default false,
   	ts BOOLEAN default false,
   	psico BOOLEAN default false, --41
   	
   	ai_si BOOLEAN default false,
   	ai_no BOOLEAN default false,
   	emb_si BOOLEAN default false,
   	emb_no BOOLEAN default false,
   	emb_meses BOOLEAN default false,
   	disc_si BOOLEAN default false,
   	disc_no BOOLEAN default false,
   	carnet_si BOOLEAN default false,
   	carnet_no BOOLEAN default false,
   	porc_disc VARCHAR(20),
   	estado_c BOOLEAN default false,
   	estado_uh BOOLEAN default false,
   	estado_v BOOLEAN default false,
   	estado_so BOOLEAN default false,
   	estado_d BOOLEAN default false,
   	estado_se BOOLEAN default false,
   	estado_ul BOOLEAN default false,
   	estado_o BOOLEAN default false,
   	estado_texto VARCHAR(200),
   	etnia_i BOOLEAN default false,
   	etnia_mo BOOLEAN default false,
   	etnia_b BOOLEAN default false,
   	etnia_a BOOLEAN default false,
   	etnia_me BOOLEAN default false,
   	etnia_o BOOLEAN default false,
   	etnia_texto VARCHAR(200),
   	
   	firma VARCHAR(200), --68
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

-- DROP FUNCTION bienestar.gestionar_formulario();

CREATE OR REPLACE FUNCTION bienestar.gestionar_formulario(p_accion text, p_num_ficha text, p_provincia text, p_ciudad text, p_parroquia text, p_est_si text, p_est_no text, p_inst_utm text, p_inst_otro text, p_inst_texto text, p_facultad text, p_carrera text, p_mod_p text, p_mod_h text, p_mod_l text, p_nivel text, p_nombres text, p_apellidos text, p_cedula text, p_celular text, p_correo text, p_edad text, p_fecha_nac text, p_nacionalidad text, p_sex_f text, p_sex_m text, p_sex_otro text, p_sex_texto text, p_identidad_genero text, p_direccion text, p_lugar_residencia text, p_contacto_ref text, p_gine text, p_lc text, p_v text, p_s text, p_hb text, p_hc text, p_pe text, p_aj text, p_ts text, p_psico text, p_ai_si text, p_ai_no text, p_emb_si text, p_emb_no text, p_emb_meses text, p_disc_si text, p_disc_no text, p_carnet_si text, p_carnet_no text, p_porc_disc text, p_estado_c text, p_estado_uh text, p_estado_v text, p_estado_so text, p_estado_d text, p_estado_se text, p_estado_ul text, p_estado_o text, p_estado_texto text, p_etnia_i text, p_etnia_mo text, p_etnia_b text, p_etnia_a text, p_etnia_me text, p_etnia_o text, p_etnia_texto text, p_firma text)
	RETURNS json
	LANGUAGE sql
AS $function$
	DECLARE
	    resultado JSON;
	    _id INT DEFAULT 0;
	BEGIN

    CASE p_accion
        WHEN 'registrar' THEN
            INSERT INTO bienestar.formulario (
                num_ficha,
                provincia, 
				ciudad, 
				parroquia, 
				est_si, 
				est_no, 
				inst_utm, 
				inst_otro, 
				inst_texto, 
				facultad, 
				carrera, 
				mod_p, 
				mod_h, 
				mod_l, 
				nivel, 
				nombres, 
				apellidos, 
				cedula, 
				celular, 
				correo, 
				edad, 
				fecha_nac, 
				nacionalidad, 
				sex_f, 
				sex_m, 
				sex_otro, 
				sex_texto,
				identidad_genero, 
				direccion, 
				lugar_residencia, 
				contacto_ref, 
				gine, 
				lc, 
				v, 
				s, 
				hb, 
				hc, 
				pe, 
				aj, 
				ts, 
				psico, 
				ai_si, 
				ai_no, 
				emb_si, 
				emb_no, 
				emb_meses, 
				disc_si, 
				disc_no, 
				carnet_si, 
				carnet_no, 
				porc_disc, 
				estado_c, 
				estado_uh, 
				estado_v, 
				estado_so, 
				estado_d, 
				estado_se, 
				estado_ul, 
				estado_o, 
				estado_texto, 
				etnia_i, 
				etnia_mo, 
				etnia_b, 
				etnia_a, 
				etnia_me, 
				etnia_o, 
				etnia_texto, 
				firma,
				creado_en
            ) VALUES (
                        p_num_ficha::INT, 
						p_provincia, 
						p_ciudad, 
						p_parroquia, 
						p_est_si::BOOLEAN, 
						p_est_no::BOOLEAN, 
						p_inst_utm::BOOLEAN, 
						p_inst_otro::BOOLEAN, 
						p_inst_texto, 
						p_facultad, 
						p_carrera, 
						p_mod_p::BOOLEAN, 
						p_mod_h::BOOLEAN, 
						p_mod_l::BOOLEAN, 
						p_nivel, 
						p_nombres, 
						p_apellidos, 
						p_cedula, 
						p_celular, 
						p_correo, 
						p_edad::INT, 
						p_fecha_nac::FEC, 
						p_nacionalidad, 
						p_sex_f::BOOLEAN, 
						p_sex_m::BOOLEAN, 
						p_sex_otro::BOOLEAN,
						p_sex_texto, 
						p_identidad_genero, 
						p_direccion, 
						p_lugar_residencia, 
						p_contacto_ref, 
						p_gine::BOOLEAN, 
						p_lc::BOOLEAN, 
						p_v::BOOLEAN, 
						p_s::BOOLEAN, 
						p_hb::BOOLEAN, 
						p_hc::BOOLEAN, 
						p_pe::BOOLEAN, 
						p_aj::BOOLEAN, 
						p_ts::BOOLEAN, 
						p_psico::BOOLEAN, 
						p_ai_si::BOOLEAN, 
						p_ai_no::BOOLEAN, 
						p_emb_si::BOOLEAN, 
						p_emb_no::BOOLEAN, 
						p_emb_meses::BOOLEAN, 
						p_disc_si::BOOLEAN, 
						p_disc_no::BOOLEAN, 
						p_carnet_si::BOOLEAN, 
						p_carnet_no::BOOLEAN, 
						p_porc_disc, 
						p_estado_c::BOOLEAN, 
						p_estado_uh::BOOLEAN, 
						p_estado_v::BOOLEAN, 
						p_estado_so::BOOLEAN, 
						p_estado_d::BOOLEAN, 
						p_estado_se::BOOLEAN, 
						p_estado_ul::BOOLEAN, 
						p_estado_o::BOOLEAN, 
						p_estado_texto, 
						p_etnia_i::BOOLEAN, 
						p_etnia_mo::BOOLEAN, 
						p_etnia_b::BOOLEAN, 
						p_etnia_a::BOOLEAN, 
						p_etnia_me::BOOLEAN, 
						p_etnia_o::BOOLEAN, 
						p_etnia_texto, 
						p_firma,
                        NOW()::FEC
                     ) RETURNING id INTO _id;

            resultado := JSON_BUILD_OBJECT(
                    'ok', TRUE,
                    'observacion', 'Formulario registrado correctamente',
                    'archivo_id', _id
                         );

        WHEN 'eliminar' THEN
            DELETE FROM bienestar.formulario WHERE num_ficha = p_num_ficha;
            resultado := JSON_BUILD_OBJECT(
                    'ok', TRUE,
                    'observacion', 'Formulario eliminado correctamente'
                         );
        ELSE
            resultado := JSON_BUILD_OBJECT(
                    'ok', FALSE,
                    'observacion', 'Acción no válida'
                         );
    END CASE;

    RETURN resultado;

	END;
$function$
